version: 2
jobs:
  integration_test:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Install make
          command: apk add --update make
      - run:
          name: Install python3
          command: apk add --update python3
      - run:
          name: Install terrascan
          command: pip3 install --upgrade terrascan
      - run:
          name: Run Integration Tests
          command: pwd && make integration_test

workflows:
  version: 2
  test_and_apply:
    jobs:
      - integration_test:
          filters:
            branches:
              only: integration_test
